# base image
from openjdk:8-jdk-alpine
# copy jar file from local to docker
copy target/config-server-0.0.1-SNAPSHOT.jar config-server-1.0.jar
# command to run jar
ENTRYPOINT ["java", "-jar","/config-server-1.0.jar"]

