spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/shared

eureka:
  client:
    serviceUrl:
#      defaultZone: http://localhost:9999/eureka
      defaultZone: http://172.20.10.4:9999/eureka
  instance:
    prefer-ip-address: true

server:
  port: 9025