spring:
  application:
    name: config-server
#  profiles:
#    active: native
  cloud:
    config:
#      server:
#        native:
#          searchLocations: classpath:/shared
      server:
        git:
          uri: https://quanzip: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@github.com/microapp-quanzip/config-folder.git
#          search-paths:
#            - shared
#         search-paths:
#            - shared
          username: quanaqtzip4@gmail.com
          password: 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
          default-label: master
  security:
    user:
      name: configserver
      password: cfcv@123
eureka:
  client:
    serviceUrl:
#      defaultZone: http://localhost:9999/eureka
      defaultZone: http://172.20.10.4:9999/eureka
  instance:
    prefer-ip-address: true

server:
  port: 9025